import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Header from "@/components/Header";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Prof.Dev",
  description: "Generated by create next app",
  icons: {
    icon:  "/dali-mask.png"
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <Header />
        <main className="px-4 py-8">{children}</main>
        <div className="flex flex-col  items-center justify-center mb-2">
          <Footer className="" />
        </div>

        <Toaster position="top-center" />
      </body>
    </html>
  );
}